baseurl = "https://lucasmelin.com"
metaDataFormat = "yaml"
title = "Lucas Melin"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = "content" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Lucas Melin"
      introSubtitle = "I love coming up with creative solutions to challenging puzzles. Passionate about helping developers succeed."
      introPhoto = "/picture.png"

    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "Projects"
        url = "projects"
        weight = 2

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 3


[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "© 2022 by Lucas Melin. All rights reserved"
  favicon = "/favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  accentColor = "bg-purple-200"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  title = "Elsewhere on the internet"
  description = "Other places you can find me online"
  linkedin = "https://linkedin.com/in/melinlucas"
  github = "https://github.com/lucasmelin"
  polywork = "https://timeline.lucasmelin.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
