[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.118.2"
HUGO_ENV = "production"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"